/**

THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY 
APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE 
COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM 
ÅgAS ISÅh WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR 
IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. 
THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM 
IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE 
COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

*/

#ifndef CMNLIB_CMNLIBCORE_CLASS_HPP__
#define CMNLIB_CMNLIBCORE_CLASS_HPP__

#include "foundations.hpp"


// A macro to disallow the copy constructor and operator= functions
// This should be used in the private: declaration for a class
#define DISALLOW_COPY_AND_ASSIGN(TypeName)	\
  TypeName(const TypeName&);                \
  void operator=(const TypeName&)


#endif	/* CMNLIB_CMNLIBCORE_CLASS_HPP__ */
