/**

THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY 
APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE 
COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM 
gAS ISh WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR 
IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. 
THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM 
IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE 
COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

*/

#ifndef CMNLIB_CMNLIBCORE_DEFINE_HPP__
#define CMNLIB_CMNLIBCORE_DEFINE_HPP__

//*****************************************************************************
// Common type declarations
//*****************************************************************************

#if _MSC_VER && !__INTEL_COMPILER && (_MSC_VER >= 1600)

#ifndef NULLPTR
#define NULLPTR nullptr
#endif

#else

#ifndef NULLPTR
#define NULLPTR 0
#endif

#endif

#ifndef CMN_CONST
#define CMN_CONST const
#endif

#endif /* CMNLIB_CMNLIBCORE_DEFINE_HPP__ */
