/**
* @file types.hpp
* @brief Types definition.
*
* @section LICENSE
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
* ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR/AUTHORS BE LIABLE FOR ANY
* DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
* ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
* @author  unknown
* @bug No known bugs.
* @version 1.0.0.0
*
*/


#ifndef CMNLIB_CMNLIBCORE_TYPES_HPP__
#define CMNLIB_CMNLIBCORE_TYPES_HPP__

//*****************************************************************************
// Common type declarations
//*****************************************************************************

#if _MSC_VER && !__INTEL_COMPILER && (_MSC_VER >= 1600)

#ifndef NULLPTR
#define NULLPTR nullptr
#endif

#else

#ifndef NULLPTR
#define NULLPTR 0
#endif

#endif

#ifndef CMN_CONST
#define CMN_CONST const
#endif

#endif // CMNLIB_CMNLIBCORE_TYPES_HPP__
