/**
* @file filesio_headers.hpp
* @brief Header of all the files related to the IO
*
* @section LICENSE
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
* ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR/AUTHORS BE LIABLE FOR ANY
* DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
* ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
* @original author Alessandro Moro
* @bug No known bugs.
* @version 0.2.0.0
*
*/

#ifndef CMNIO_FILESIO_HEADERS_HPP__
#define CMNIO_FILESIO_HEADERS_HPP__

#include "ConfigLineIO.hpp"
#include "FishEyeLensCorrectionIO.hpp"
#include "LineDirectionIO.hpp"
#include "Mesh3DxyzxyIO.hpp"
#include "RemapIO.hpp"
#include "Points2DIO.hpp"
#include "Points3DIO.hpp"
#include "Pairs2DIO.hpp"
#include "Node6DOFT3R3.hpp"
#include "VertexIONaive.hpp"
#include "VertexOrientedIONaive.hpp"

#endif /* CMNIO_FILESIO_HEADERS_HPP__ */
